- name: configure sudo email address
  lineinfile:
    path: /etc/sudoers.d/99-sudoers-config
    create: yes
    line: "Defaults mailfrom=\"{{ ansible_hostname }}@douglas.mcgill.ca\""
    validate: 'visudo -cf %s'

- name: add cicadministrators to sudoers
  lineinfile:
    path: /etc/sudoers.d/99-sudoers-config
    line: "%cicadministrators ALL=(ALL) NOPASSWD:ALL"
    validate: 'visudo -cf %s'
